// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

/************************************************************/
/**
 * 
 */
public class IOperatorFaultView {
	/**
	 * 
	 * @return 
	 */
	public void getFault() {
	}
};
