// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

/************************************************************/
/**
 * 
 */
public interface IOperatorEnvironmentView {
	
	/**
	 * 
	 * @return 
	 */
	public String getRoverLocation();

	/**
	 * 
	 * @return 
	 */
	public String getMissionProgress();
	
	/**
	 * 
	 * @return 
	 */
	public String getFault();
	
};
