// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

/************************************************************/
/**
 * 
 */
public interface IOperatorRewardPointsView {
	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void notifyRewardPoints(int[] rewardPoints);

	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void resetRewardPoints(int[] rewardPoints);
};
