// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

/************************************************************/
/**
 * 
 */
public interface IOperatorEnvironmentView {
	/**
	 * 
	 * @return 
	 */
	public void updateLocation();

	/**
	 * 
	 * @return 
	 */
	public void updateMissionProgress();
};
