// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

import java.util.List;

import project.Point;
import rover.Model.Rover;
/************************************************************/
/**
 * 
 */
public interface IOperatorCreateMissionView {
	/**
	 * 
	 * @param points 
	 * @param roverName 
	 * @return 
	 */
	public void createMission(List<Point> points, Rover rover);
};
