// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

import rover.View.IOperatorRewardPointsView;

/************************************************************/
/**
 * 
 */
public class NTOperatorRewardPointsView implements IOperatorRewardPointsView {
	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void notifyRewardPoints(int rewardPoints) {
	}

	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void resetRewardPoints(int rewardPoints) {
	}
};
