// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

import rover.View.IOperatorEnvironmentView;

/************************************************************/
/**
 * 
 */
public class NTOperatorEnvironmentView implements IOperatorEnvironmentView {
	/**
	 * 
	 * @return 
	 */
	public String getRoverLocation() {
		return "Location of the Rovers";
	}

	/**
	 * 
	 * @return 
	 */
	public String getMissionProgress() {
		return "progress of the Rovers";
	}
	
	/**
	 * 
	 * @return 
	 */
	public String getFault() {
		return "Faults of the rover";
	}
};
