// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

import rover.View.IOperatorEnvironmentView;

/************************************************************/
/**
 * 
 */
public class NTOperatorEnvironmentView implements IOperatorEnvironmentView {
	/**
	 * 
	 * @return 
	 */
	public void updateLocation() {
	}

	/**
	 * 
	 * @return 
	 */
	public void updateMissionProgress() {
	}
};
