// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

import project.Point;
import rover.Controller.IMissionManager;
import rover.Controller.StrategyFactory;
import rover.View.IOperatorCreateMissionView;
import rover.View.IOperatorEnvironmentView;
import rover.View.IOperatorFaultView;
import rover.View.IOperatorRewardPointsView;

/************************************************************/
/**
 * 
 */
public class Operator implements rover.Controller.IOperatorFaultView {
	/**
	 * 
	 */
	public IOperatorCreateMissionView ioperatorrewardpointsview;
	/**
	 * 
	 */
	public IOperatorRewardPointsView ioperatorrewardpointsview;
	/**
	 * 
	 */
	public IOperatorEnvironmentView ioperatorenvironmentview;
	/**
	 * 
	 */
	public IOperatorFaultView ioperatorfaultview;
	/**
	 * 
	 */
	public StrategyFactory strategyfactory;

	/**
	 * 
	 * @return 
	 */
	public void updateLocation() {
	}

	/**
	 * 
	 * @return 
	 */
	public void updateMissionProgress() {
	}

	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void notifyRewardPoints(int[] rewardPoints) {
	}

	/**
	 * 
	 * @param points 
	 * @param roverName 
	 */
	public void createMission(Point points, String roverName) {
	}
};
