// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

import rover.View.Operator;

/************************************************************/
/**
 * 
 */
public class OperatorFactory {
	/**
	 * 
	 */
	private Operator nonTechnicalOperator = null;
	/**
	 * 
	 */
	private Operator technicalOperator = null;
	/**
	 * 
	 */
	public Operator operator = null;

	/**
	 * 
	 * @return 
	 */
	public Operator getNonTechnicalOperatorInstance() {
		if (nonTechnicalOperator == null) {
			nonTechnicalOperator = new Operator("non-technical");
		} 
		return nonTechnicalOperator;
	}
	

	/**
	 * 
	 * @return 
	 */
	public Operator getTechnicalOperatorInstance() {
		if (technicalOperator == null) {
			technicalOperator = new Operator("technical");
		} 
		return technicalOperator;
	}
};
