// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

import rover.View.Operator;

/************************************************************/
/**
 * 
 */
public class OperatorFactory {
	/**
	 * 
	 */
	private Operator nonTechnicalOperator;
	/**
	 * 
	 */
	private Operator technicalOperator;
	/**
	 * 
	 */
	public Operator operator;

	/**
	 * 
	 * @return 
	 */
	public Operator getNonTechnicalOperatorInstance() {
	}

	/**
	 * 
	 * @return 
	 */
	public Operator getTechnicalOperatorInstance() {
	}
};
