// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

import rover.View.IOperatorCreateMissionView;

/************************************************************/
/**
 * 
 */
public class TOperatorCreateMissionView implements IOperatorCreateMissionView {
};
