// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

import java.util.List;
import rover.Controller.IMissionManager;
import rover.Model.Rover;
import rover.View.IOperatorMissionManagerView;
import rover.Controller.IStrategy;
import project.Point;

/************************************************************/
/**
 * 
 */
public class TOperatorMissionManagerView implements IOperatorMissionManagerView {


	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean removeMission(Rover rover) {
		return true;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean removeAllMissions() {
		return true;
	}

	/**
	 * 
	 * @return 
	 * @param rover 
	 */
	public boolean pauseMission(Rover rover) {
		return true;
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean continueMission(Rover rover) {
		return true;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean pauseAllMissions() {
		return true;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean continueAllMissions() {
		return true;
	}

	/**
	 * 
	 * @param rover 
	 */
	public void changeStrategy(Rover rover) {
	}

	/**
	 * 
	 * @param rover 
	 * @param strategy 
	 */
	public void changeStrategy(Rover rover, IStrategy strategy) {
	}

	@Override
	public boolean createMission(List<Point> points, Rover rover, IMissionManager missionManager, IStrategy strategy) {
		return missionManager.createMission(points, rover, strategy);
	}
};
