// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

import rover.View.IOperatorEnvironmentView;

/************************************************************/
/**
 * 
 */
public class TOperatorEnvironmentView implements IOperatorEnvironmentView {

	/**
	 * 
	 * @return 
	 */
	public String getRoverLocation() {
		return "Location of the Rovers";
	}

	/**
	 * 
	 * @return 
	 */
	public String getMissionProgress() {
		return "progress of the Rovers";
	}
	
	/**
	 * 
	 * @return 
	 */
	public String getFault() {
		return "Retourn an error because the NTOperator cannot have this information";
	}
	
};
