// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.View;

import rover.View.IOperatorRewardPointsView;

/************************************************************/
/**
 * 
 */
public class TOperatorRewardPointsView implements IOperatorRewardPointsView {
	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void notifyRewardPoints(int[] rewardPoints) {
		for (int i = 0; i < rewardPoints.length; i++) {
			System.out.println("Rover " + (i+1) + " has currently " + rewardPoints[i] + " rewardpoints");
		}
	}

	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void resetRewardPoints(int[] rewardPoints) {
	}
};
