// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public interface IOperatorCreateMissionView {
	/**
	 * 
	 * @param points 
	 * @param roverName 
	 * @return 
	 */
	public void createMission(int points, String roverName);
};
