// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import Point;
import project.Point;

/************************************************************/
/**
 * 
 */
public interface IPointAchieved {
	/**
	 * 
	 * @param savePoint 
	 * @return 
	 */
	public void achievedPoint(Point savePoint);

	/**
	 * 
	 * @param savePoint 
	 * @return 
	 * @param roverName 
	 */
	public void achievedPoint(Point savePoint, String roverName);
};
