// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import Point;

/************************************************************/
/**
 * 
 */
public interface IPointAchieved {
	/**
	 * 
	 * @param savePoint 
	 * @return 
	 */
	public void achievedPoint(Point savePoint);
};
