// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import Point;
import project.Point;

/************************************************************/
/**
 * 
 */
public interface IRewardPoints {
	/**
	 * 
	 * @param name 
	 * @param point 
	 * @return 
	 */
	public void calculateRewardPoints(String name, Point point);

	/**
	 * 
	 * @param  
	 * @return 
	 */
	public void updateRewardPoints(int null) ;
};
