// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import Point;
import project.Point;

/************************************************************/
/**
 * 
 */
public interface IRoverLocation {
	/**
	 * 
	 * @param name 
	 * @return 
	 */
	public Point getLocation(String name);
};
