// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import Point;
import project.Point;

/************************************************************/
/**
 * 
 */
public interface IRoverStrategy {
	/**
	 * 
	 * @param savePoint 
	 * @return 
	 */
	public void goTo(Point savePoint);
};
