// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import IMissionAchieved;
import IStrategyManager;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class MissionManager implements IMissionAchieved {
	/**
				 * 
				 */
				public List<Mission> list<mission>;
};
