// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import Point;

/************************************************************/
/**
 * 
 */
public class Mission {
	/**
	 * 
	 */
	public Point[] points;
	/**
	 * 
	 */
	public String roverName;
};
