// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import IOperatorEnvironmentView;

/************************************************************/
/**
 * 
 */
public class NTOperatorEnvironmentView implements IOperatorEnvironmentView {
};
