// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import IOperatorCreateMissionView;
import IOperatorFaultView;
import Point;
import IOperatorEnvironmentView;
import IOperatorRewardPointsView;

/************************************************************/
/**
 * 
 */
public class Operator implements IOperatorFaultView {
	/**
	 * 
	 */
	public IOperatorFaultView ioperatorfaultview;
	/**
	 * 
	 */
	public IOperatorEnvironmentView ioperatorenvironmentview;
	/**
	 * 
	 */
	public IOperatorRewardPointsView ioperatorrewardpointsview;

	/**
	 * 
	 * @return 
	 */
	public void updateLocation() {
	}

	/**
	 * 
	 * @return 
	 */
	public void updateEnvironmentStatus() {
	}

	/**
	 * 
	 * @return 
	 */
	public void updateMissionProgress() {
	}

	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void notifyRewardPoints(int[] rewardPoints) {
	}

	/**
	 * 
	 * @param points 
	 * @param roverName 
	 */
	public void createMission(Point points, String roverName) {
	}
};
