// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import IRewardPoints;

/************************************************************/
/**
 * 
 */
public class Procedure B implements IRewardPoints
 {
				/**
				 * 
				 */
				public int rewardPoint;
};
