// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import IRewardPoints;
import IRewardPointsManagar;
import IRoverLocation;
import Procedure A;
import Procedure B;
import java.util.Map;

/************************************************************/
/**
 * 
 */
public class RewardPointsManager implements IRewardPointsManagar {
	/**
				 * 
				 */
				private Procedure A procedureA;
	/**
				 * 
				 */
				private Procedure B procedureB;
	/**
	 * 
	 */
	private IRewardPoints currentProcedure;

	/**
	 * 
	 */
	public map<String, int> map<string, int>;
	/**
	 * 
	 * @return 
	 */
	private void updateProcedure() {
	}

	/**
	 * 
	 * @param additionalPoint 
	 * @param nameRover 
	 * @return 
	 */
	public void setRewardPoints(int additionalPoint, String nameRover) {
	}
};
