// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import IOperatorFaultView;
import IPointAchieved;
import IRoverLocation;
import IRoverStrategy;
import project.AbstractRobot;

/************************************************************/
/**
 * 
 */
public class Rover extends AbstractRobot implements IRoverStrategy, IRoverLocation {
};
