// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import IMissionAchieved;
import IPointAchieved;
import IStrategyManager;
import Mission;
import Point;
import Strategy;
import project.Point;

/************************************************************/
/**
 * 
 */
public class StrategyManager implements IPointAchieved, IStrategyManager {
	/**
	 * 
	 */
	public Strategy[] strategy;

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	private void initialiseStrategy(Mission mission) {
	}

	/**
	 * 
	 * @param roverName 
	 * @return 
	 */
	private boolean checkRoverAvailability(String roverName) {
	}

	/**
	 * 
	 * @param roverName 
	 * @return 
	 */
	private Point defineNextPoint(String roverName) {
	}

	/**
	 * 
	 * @param point 
	 * @param roverName 
	 * @return 
	 */
	private void providePointToRover(Point point, String roverName) {
	}

	/**
	 * 
	 * @return 
	 */
	private void mainProcedure() {
	}
};
