// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import Mission;
import Point;
import project.Point;

/************************************************************/
/**
 * 
 */
public class Strategy {
	/**
	 * 
	 */
	private Mission mission;
	/**
	 * 
	 */
	private Point pointHistory;

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public void setMission(Mission mission) {
	}

	/**
	 * 
	 * @param point 
	 * @return 
	 */
	public void addPointHistory(Point point) {
	}

	/**
	 * 
	 * @return 
	 */
	public Point getLastPoint() {
	}
};
