// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import IOperatorCreateMissionView;

/************************************************************/
/**
 * 
 */
public class TOperatorCreateMissionView implements IOperatorCreateMissionView {
};
