// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import IOperatorEnvironmentView;

/************************************************************/
/**
 * 
 */
public class TOperatorEnvironmentView implements IOperatorEnvironmentView {
};
