// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import rover.Controller.IAccessManager;
import rover.Model.Rover;

/************************************************************/
/**
 * 
 */
public class AccessManager implements IAccessManager {
	/**
	 * 
	 */
	public undefined[] listAccessController;

	/**
	 * 
	 * @param listAreaController 
	 */
	public void AccessManager(undefined[] listAreaController) {
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public void isInAreaController(Rover rover) {
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public void releaseAccess(Rover rover) {
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public void acquireAccess(Rover rover) {
	}
};
