// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import rover.Controller.IAccessManager;
import rover.Model.Rover;
import rover.AccessController;

/************************************************************/
/**
 * 
 */
public class AccessManager implements IAccessManager {
	/**
	 * 
	 */
	public AccessController[] listAccessController;

	/**
	 * 
	 * @param listAreaController 
	 */
	public void AccessManager(AccessController[] listAreaController) {
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean isInAreaController(Rover rover) {
		//need to figure out if List or array
		for (Iterator<AccessController> iter = listAccessController.iterator; iter.hasNext(); ) {
			AccessController ac = iter.next();
			if(ac.isInArea(rover) && !ac.isTheOwner(rover)) {
				return ac;
			}
		}
		return null;
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public void releaseAccess(Rover rover) {
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public void acquireAccess(Rover rover) {
	}

	@Override
	public void manageAccess(Rover rover) {
		// TODO Auto-generated method stub
		
	}
};
