// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import project.Point;
import rover.Model.Rover;
import rover.Model.Mission;

/************************************************************/
/**
 * 
 */
public interface IMissionManager {
	/**
	 * 
	 * @param points 
	 * @return 
	 * @param rover 
	 */
	public boolean createMission(Point[] points, Rover rover);

	/**
	 * @param mission            
	 * @return            
	 */
	public boolean removeAllMissions();

	/**
	 * @param mission            
	 * @return            
	 */
	public boolean pauseAllMissions();

	/**
	 * 
	 * @return 
	 */
	public boolean continueAllMissions();

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean pauseMission(Rover rover);

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean continueMission(Rover rover);

	/**
	 * 
	 * @param rover 
	 * @return 
	 * @param mission 
	 */
	public boolean removeMission(Rover rover);
};
