// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import project.Point;
import rover.Model.Rover;
import rover.Model.Mission;
import rover.Controller.IStrategy;
import java.util.List;

/************************************************************/
/**
 * 
 */
public interface IMissionManager {
	/**
	 * 
	 * @return 
	 */
	public boolean removeAllMissions();

	/**
	 * 
	 * @return 
	 */
	public boolean pauseAllMissions();


	/**
	 * 
	 * @return 
	 */
	public boolean continueAllMissions();

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean pauseMission(Rover rover);
	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean continueMission(Rover rover);
	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean removeMission(Rover rover);

	/**
	 * 
	 * @param points 
	 * @return 
	 * @param rover 
	 * @param strategy 
	 */
	public boolean createMission(List<Point> points, Rover rover, Integer strategy);
	
	public List<Rover> getRovers();
};
