// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import project.Point;
import rover.Model.Rover;

/************************************************************/
/**
 * 
 */
public interface INotifyOperator {
	/**
	 * 
	 * @return 
	 */
	public void notifyFault(Rover rover, String status);
	public void notifyLocation(Rover rover, Point location);
	public void notifyMissionProgress(Rover rover, Integer progress);
};
