// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

/************************************************************/
/**
 * 
 */
public interface INotifyOperator {
	/**
	 * 
	 * @return 
	 */
	public void notifyFault(String status);
	public void notifyLocation(String location);
	public void notifyMissionProgress(String progress);
};
