// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

/************************************************************/
/**
 * 
 */
public interface IOperatorFaultView {
	/**
	 * 
	 * @return 
	 */
	public void notifyFault();
};
