// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import rover.Model.Rover;

/************************************************************/
/**
 * 
 */
public interface IStrategy {
	/**
	 * 
	 * @param rover 
	 */
	public void applyBehaviour(Rover rover);
};
