// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import rover.Model.LogicalArea;
import rover.Model.PhysicalArea;
import rover.Model.IRoverLocator;

/************************************************************/
/**
 * 
 */
public interface IVisitorProcedure {
	
	public void visit(PhysicalArea physicalArea, IRoverLocator rover);

	/**
	 * 
	 * @param logicalArea 
	 * @param rover 
	 * @return 
	 */
	public void visit(LogicalArea logicalArea, IRoverLocator rover);

	/**
	 * 
	 * @param physicalArea 
	 * @param rover 
	 * @return 
	 */


};
