// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import java.util.List;
import project.Point;
import rover.Controller.IMissionManager;
import rover.Model.Mission;
import rover.Model.Rover;

/************************************************************/
/**
 * 
 */
public class MissionManager implements IMissionManager {
	/**
	 * 
	 */
	public List<Mission> missionList;
	/**
	 * 
	 */
	public List<Rover> roverList;

	/**
	 * 
	 * @param rovers 
	 */
	public MissionManager(Rover[] rovers) {
	}

	/**
	 * 
	 * @return 
	 */
	public List<Mission> getMissions() {
		return missionList;
	}

	/**
	 * 
	 * @return 
	 */
	public List<Rover> getRovers() {
		return roverList;
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean checkRoverAvailability(Rover rover) {
		return rover.isSleeping();
	}

	/**
	 * @param mission         
	 * @return         
	 */
	public boolean removeAllMissions() {
		for (int i = 0; i < missionList.size(); i++) {
			missionList.add(i, null);
		}
		return true;
	}

	/**
	 * @param mission         
	 * @return         
	 */
	public boolean pauseAllMissions() {
		for (Rover rover: roverList) {
			rover.pauseRover();
		}
		return true;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean continueAllMissions() {
		for (Rover rover  : roverList) {
			rover.continueRover();
		}
		return true;
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean pauseMission(Rover rover) {
		boolean isPaused = rover.pauseRover();
		return isPaused;
	}

	/**
	 * 
	 * @param points 
	 * @return 
	 * @param rover 
	 */
	public boolean createMission(Point[] points, Rover rover) {
		Mission mission = new Mission(points);
		rover.provideMission(mission, null);
		boolean isAdded = missionList.add(mission);
		return isAdded;
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean continueMission(Rover rover) {
		boolean isPaused = rover.pauseRover();
		return isPaused;
	}

	/**
	 * 
	 * @param rovers 
	 */
	public void MissionManager(Rover[] rovers) {
	}


	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public boolean removeMission(Rover rover) {
		boolean isRemoved = rover.removeMission();
		return isRemoved;
	}


};
