// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import java.util.Map;
import rover.Controller.IRewardPointsManagar;
import rover.Controller.IVisitorProcedure;
import rover.Controller.runnable;
import rover.Model.IRoverLocator;
import rover.Model.IVisitableArea;
import rover.View.IOperatorRewardPointsView;
import java.lang.Runnable;

/************************************************************/
/**
 * 
 */
public class RewardPointsManager implements IRewardPointsManagar, Runnable
 {
				/**
				 * 
				 */
				private IVisitorProcedure[] procedureList;
				/**
				 * 
				 */
				private map<Rover, int> map<Rover, int>;
};
