// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import java.util.concurrent.TimeUnit;

import rover.Controller.IStrategy;
import rover.Model.IVisitableArea;
import rover.Model.Rover;

/************************************************************/
/**
 * 
 */
public class Strategy2 implements IStrategy {
	/**
	 * 
	 */
	private IVisitableArea currentArea;
	
	public Strategy2() {
		currentArea = null;
	}
	
	public void pauseRover2s(Rover rover){
		rover.pauseRover();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		rover.continueRover();
		
	}
	
	private void enterNewAreaRule(Rover rover) {
		if(!rover.getAreas().isEmpty()) {
			//System.out.println(currentArea);
			if(currentArea != rover.getAreas().get(0)) {
				this.pauseRover2s(rover);
				currentArea = rover.getAreas().get(0);
			}
		}
	}


	@Override
	public void applyBehaviour(Rover rover) {
		//System.out.println(rover.getPosition());
		if(!rover.isSleeping()) { // the rover has a mission to perform
			if(rover.isAtPosition(rover.getDestination()) && !rover.isPaused()) {
				rover.goToNextPoint();
			}
			rover.getAccessManager().manageAccess(rover);
			enterNewAreaRule(rover);
		}
	}
};
