// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import rover.Controller.IStrategy;
import rover.Model.IVisitableArea;

/************************************************************/
/**
 * 
 */
public class Strategy2 implements IStrategy {
	/**
	 * 
	 */
	public IVisitableArea currentArea;
};
