// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import rover.Controller.IStrategy;
import rover.Model.Rover;

/************************************************************/
/**
 * 
 */
public class Strategy1 implements IStrategy {
	/**
	 * 
	 * @param rover 
	 */
	public void applyBehaviour(Rover rover) {
	}
};
