// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;


import rover.Controller.IStrategy;

/************************************************************/
/**
 * 
 */
public class StrategyFactory {
	
	/**
	 * 
	 * @param number 
	 * @return 
	 */
	public IStrategy createStrategy(Integer number) {
		
		IStrategy strat = null;
		if(number == 1) {
			strat = new Strategy1();
		}
		if(number == 2) {
			strat = new Strategy2();
		}
		return strat;
	}
};
