// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Controller;

import rover.Controller.IStrategy;

/************************************************************/
/**
 * 
 */
public class StrategyFactory {
	/**
	 * 
	 */
	public void createStrategy() {
	}
};
