// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.Mission;

/************************************************************/
/**
 * 
 */
public interface IMissionManager {
	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean createMission(Mission mission);

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean removeMission(Mission mission);

	/**
	 * 
	 * @return 
	 */
	public boolean removeAllMissions();

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean pauseMission(Mission mission);

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean continueMission(Mission mission);

	/**
	 * 
	 * @return 
	 */
	public boolean pauseAllMissions();

	/**
	 * 
	 * @return 
	 */
	public boolean continueAllMissions();
};
