// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public interface IMissionAchieved {
	/**
	 * 
	 * @return 
	 */
	public void achievedMission();

	/**
	 * 
	 * @return 
	 */
	public void achievedPoint();
};
