// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.Point;

/************************************************************/
/**
 * 
 */
public interface IRewardPoints {
	/**
	 * 
	 * @param name 
	 * @param point 
	 * @return 
	 */
	public void calculateRewardPoints(String name, Point point);

	/**
	 * 
	 * @param  
	 * @return 
	 */
	public void updateRewardPoints(int[] null) ;

	

	

	/**
	 * 
	 * @param points 
	 * @return 
	 */
	public void updateRewardPoints(int[] points);
};
