// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public interface IRewardPointsManagar {
	/**
	 * 
	 * @return 
	 */
	public void updateRewardPoints();
};
