// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import java.util.List;
import project.IMissionAchieved;
import project.IMissionManager;
import project.IStrategyManager;
import project.Mission;

/************************************************************/
/**
 * 
 */
public class MissionManager implements IMissionAchieved, IMissionManager {
	/**
				 * 
				 */
				public List<Mission> list<mission>;

	/**
	 * 
	 * @return 
	 */
	public void achievedMission() {
	}

	/**
	 * 
	 * @return 
	 */
	public void achievedPoint() {
	}
};
