// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import java.util.List;

import project.Point;

/************************************************************/
/**
 * 
 */
public class Mission {
	/**
	 * 
	 */
	private List<Point> points;
	/**
	 * 
	 */
	private String roverName;
	
	public Mission(List<Point> points, String roverName){
		this.points = points;
		this.roverName = roverName;
	}
	
	public List<Point> getPoints(){
		return this.points;
	}
	
	public String getRoverName(){
		return this.roverName;
	}
};
