// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.IOperatorEnvironmentView;

/************************************************************/
/**
 * 
 */
public class NTOperatorEnvironmentView implements IOperatorEnvironmentView {
};
