// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.IOperatorCreateMissionView;
import project.IOperatorEnvironmentView;
import project.IOperatorFaultView;
import project.IOperatorRewardPointsView;
import project.Point;

/************************************************************/
/**
 * 
 */
public class Operator implements IOperatorFaultView {
	/**
	 * 
	 */
	public IOperatorCreateMissionView ioperatorrewardpointsview;
	/**
	 * 
	 */
	public IOperatorRewardPointsView ioperatorrewardpointsview;
	/**
	 * 
	 */
	public IOperatorEnvironmentView ioperatorenvironmentview;
	/**
	 * 
	 */
	public IOperatorFaultView ioperatorfaultview;

	/**
	 * 
	 * @return 
	 */
	public void updateLocation() {
	}

	/**
	 * 
	 * @return 
	 */
	public void updateEnvironmentStatus() {
	}

	/**
	 * 
	 * @return 
	 */
	public void updateMissionProgress() {
	}

	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void notifyRewardPoints(int[] rewardPoints) {
	}

	/**
	 * 
	 * @param points 
	 * @param roverName 
	 */
	public void createMission(Point points, String roverName) {
	}
};
