// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.IRewardPoints;
import project.Point;

/************************************************************/
/**
 * 
 */
public class ProcedureB implements IRewardPoints {
	/**
	 * 
	 */
	public int rewardPoint;

	/**
	 * 
	 * @param  
	 * @return 
	 */
	public void updateRewardPoints(int null) {
	}
	}

	/**
	 * 
	 * @param name 
	 * @param point 
	 * @return 
	 */
	public void calculateRewardPoints(String name, Point point) {
	}

	/**
	 * 
	 * @param points 
	 * @return 
	 */
	public void updateRewardPoints(int[] points) {
	}
};
