// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import java.util.Map;
import project.IRewardPoints;
import project.IRewardPointsManagar;
import project.IRoverLocation;
import project.ProcedureA;
import project.ProcedureB;

/************************************************************/
/**
 * 
 */
public class RewardPointsManager implements IRewardPointsManagar {
	/**
	 * 
	 */
	private ProcedureA procedureA;
	/**
	 * 
	 */
	private ProcedureB procedureB;
	/**
	 * 
	 */
	private IRewardPoints currentProcedure;

	/**
	 * 
	 */
	public map<String, int> map<string, int>;
	/**
	 * 
	 * @return 
	 */
	private void updateProcedure() {
	}

	/**
	 * 
	 * @param additionalPoint 
	 * @param nameRover 
	 * @return 
	 */
	public void setRewardPoints(int additionalPoint, String nameRover) {
	}
};
