// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.AbstractRobot;
import project.IOperatorFaultView;
import project.IPointAchieved;
import project.IRoverLocation;
import project.IRoverStrategy;

/************************************************************/
/**
 * 
 */
public class Rover extends AbstractRobotSimulator implements IRoverStrategy, IRoverLocation {
};
