// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.IMissionAchieved;
import project.IPointAchieved;
import project.IStrategyManager;
import project.Mission;
import project.Point;
import project.Strategy;

/************************************************************/
/**
 * 
 */
public class StrategyManager implements IPointAchieved, IStrategyManager {
	/**
	 * 
	 */
	public Strategy[] strategy;

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	private void initialiseStrategy(Mission mission) {
	}

	/**
	 * 
	 * @param roverName 
	 * @return 
	 */
	private boolean checkRoverAvailability(String roverName) {
	}

	/**
	 * 
	 * @param roverName 
	 * @return 
	 */
	private Point defineNextPoint(String roverName) {
	}

	/**
	 * 
	 * @param point 
	 * @param roverName 
	 * @return 
	 */
	private void providePointToRover(Point point, String roverName) {
	}

	/**
	 * 
	 * @return 
	 */
	private void mainProcedure() {
	}
};
