// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.IOperatorRewardPointsView;

/************************************************************/
/**
 * 
 */
public class TOperatorRewardPointsView implements IOperatorRewardPointsView {
	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void notifyRewardPoints(int rewardPoints) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoints() {
	}

	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void resetRewardPoints(int rewardPoints) {
	}
};
