// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import project.Point;
import rover.Model.IArea;

/************************************************************/
/**
 * 
 */
public abstract class AbstractArea implements IArea {
	/**
	 * 
	 */
	private Point position;
	/**
	 * 
	 */
	private double width;
	/**
	 * 
	 */
	private double height;
	/**
	 * 
	 */
	private String areaType;

	/**
	 * 
	 * @param position 
	 * @param width 
	 * @param height 
	 * @param areaType 
	 */
	public abstract void abstractArea(Point position, double width, double height, String areaType);

	/**
	 * 
	 * @return 
	 */
	public abstract Point getPosition();

	/**
	 * 
	 * @return 
	 */
	public abstract double getWidth();

	/**
	 * 
	 * @return 
	 */
	public double getHeight() {
	}
};
