// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import project.Point;
import rover.Model.IArea;

/************************************************************/
/**
 * 
 */
public abstract class AbstractArea implements IArea {
	/**
	 * 
	 */
	private Point position;
	/**
	 * 
	 */
	private double width;
	/**
	 * 
	 */
	private double height;
	/**
	 * 
	 */
	private String areaType;

	/**
	 * Constructor creats abstract area
	 * @param position 
	 * @param width 
	 * @param height 
	 * @param areaType 
	 */
	public void abstractArea(Point position, double width, double height, String areaType) {
		position = this.position;
		width = this.width;
		height = this.height;
		areaType = this.areaType;
	}

	/**
	 * 
	 * @return 
	 */
	public abstract Point getPosition();

	/**
	 * 
	 * @return 
	 */
	public abstract double getWidth();

	/**
	 * 
	 * @return 
	 */
	public abstract double getHeight();

	/**
	 * 
	 * @return 
	 */
	public abstract String getAreaType();
};
