// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import project.Point;
import rover.Controller.IVisitorProcedure;
import rover.Model.IArea;

/************************************************************/
/**
 * 
 */
public abstract class AbstractArea implements IArea, IVisitableArea {
	/**
	 * 
	 */
	private Point position;
	/**
	 * 
	 */
	private double width;
	/**
	 * 
	 */
	private double height;
	/**
	 * 
	 */
	private String areaType;

	/**
	 * Constructor creats abstract area
	 * @param position  
	 * @param width  
	 * @param height  
	 * @param areaType  
	 */
	public AbstractArea(Point position, double width, double height, String areaType) {
		this.position = position;
		this.width = width;
		this.height = height;
		this.areaType = areaType;
	}

	/**
	 * 
	 * @return 
	 */
	public Point getPosition() {
		return position;
	}

	/**
	 * 
	 * @return 
	 */
	public double getWidth() {
		return width;
	}

	/**
	 * 
	 * @return 
	 */
	public double getHeight() {
		return height;
	}

	/**
	 * 
	 * @return 
	 */
	public String getAreaType() {
		return areaType;
	}
	
}
