// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import project.Point;

/************************************************************/
/**
 * 
 */
public interface IArea {
	/**
	 * 
	 * @param point 
	 * @return 
	 */
	public boolean isInArea(Point point);
};
