// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import java.util.List;

import rover.Model.IVisitableArea;

/************************************************************/
/**
 * 
 */
public interface IRoverLocator {
	/**
	 * 
	 * @return 
	 */
	public List<IVisitableArea> getAreas();

	/**
	 * 
	 * @return 
	 */
	public String getName(); 
};
