// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import rover.Model.IVisitableArea;

/************************************************************/
/**
 * 
 */
public interface IRoverLocator {
	/**
	 * 
	 * @return 
	 */
	public IVisitableArea[] getAreas();

	/**
	 * 
	 * @return 
	 */
	public String getName();
};
