// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import rover.Controller.IVisitorProcedure;
import rover.Model.IRoverLocator;

/************************************************************/
/**
 * 
 */
public interface IVisitableArea {
	/**
	 * 
	 * @param procedure 
	 * @param rover 
	 * @return 
	 */
	public void accept(IVisitorProcedure procedure, IRoverLocator rover);
};
