// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import project.Point;
import rover.Model.AbstractArea;

/************************************************************/
/**
 * 
 */
public class LogicalArea extends AbstractArea {
	/**
	 * 
	 * @param position 
	 * @param width 
	 * @param height 
	 * @param areaType 
	 */
	public void logicalArea(Point position, double width, double height, String areaType) {
	}

	/**
	 * 
	 * @param point 
	 * @return 
	 */
	public boolean contains(Point point) {
	}

	/**
	 * 
	 * @return 
	 */
	public String getAreaType() {
	}
};
