// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import project.Point;

/************************************************************/
/**
 * 
 */
public class Mission {
	/**
	 * 
	 */
	public Point[] pointsToReach;
	/**
	 * 
	 */
	public Point[] pointsReached;

	/**
	 * 
	 * @param pointsToReach 
	 */
	public Mission(Point[] pointsToReach) {
		this.pointsToReach = pointsToReach;
	}

	/**
	 * 
	 * @return 
	 */
	public Point[] getPointsToReach() {
	}

	/**
	 * 
	 * @return 
	 */
	public void pointReached() {
	}

	/**
	 * 
	 * @return 
	 */
	public Point getNextPoint() {
	}

	/**
	 * 
	 * @param pointsToReach 
	 */
	public void Mission(Point[] pointsToReach) {
	}

	/**
	 * 
	 * @return 
	 */
	public Point[] getPointsReached() {
	}
};
