// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import project.Point;
import rover.Model.AbstractArea;
import rover.Model.LogicalArea;

/************************************************************/
/**
 * 
 */
public class PhysicalArea extends AbstractArea {
	/**
	 * 
	 */
	private rover.Model.PhysicalArea[] nestedAreas;
	/**
	 * 
	 */
	private LogicalArea[] nestedLogicalAreas;

	/**
	 * 
	 * @param position 
	 * @param width 
	 * @param height 
	 * @param areaType 
	 * @param nestedLogicalArea 
	 * @param nestedPhysicalAreas 
	 */
	public void physicalArea(Point position, double width, double height, String areaType,
			LogicalArea nestedLogicalArea, rover.Model.PhysicalArea nestedPhysicalAreas) {
	}

	/**
	 * 
	 * @param point 
	 * @return 
	 */
	public boolean contains(Point point) {
		return true;
	}

	/**
	 * 
	 * @return 
	 */
	public String getAreaType() {
		return "";
	}

	@Override
	public boolean isInArea(Point point) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void abstractArea(Point position, double width, double height, String areaType) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Point getPosition() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public double getWidth() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public double getHeight() {
		// TODO Auto-generated method stub
		return 0;
	}
};
