// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import project.Point;
import rover.Model.AbstractArea;
import rover.Model.LogicalArea;

/************************************************************/
/**
 * 
 */
public class PhysicalArea extends AbstractArea {
	/**
	 * 
	 */
	private rover.Model.PhysicalArea[] nestedAreas;
	/**
	 * 
	 */
	private LogicalArea[] nestedLogicalAreas;

	/**
	 * 
	 * @param position 
	 * @param width 
	 * @param height 
	 * @param areaType 
	 * @param nestedLogicalArea 
	 * @param nestedPhysicalAreas 
	 */
	public void physicalArea(Point position, double width, double height, String areaType,
			LogicalArea nestedLogicalArea, rover.Model.PhysicalArea nestedPhysicalAreas) {
	}

	/**
	 * 
	 * @param point 
	 * @return 
	 */
	public boolean contains(Point point) {
	}

	/**
	 * 
	 * @return 
	 */
	public String getAreaType() {
	}
};
