// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover.Model;

import project.AbstractRobotSimulator;
import project.Point;
import rover.Controller.IAccessManager;
import rover.Controller.IOperatorFaultView;
import rover.Controller.IStrategy;
import rover.Controller.Strategy1;
import rover.Model.AbstractArea;
import rover.Model.IRoverLocator;
import rover.Model.IRoverManager;
import rover.Model.IVisitableArea;
import rover.Model.Mission;

/************************************************************/
/**
 * 
 */
public class Rover extends AbstractRobotSimulator implements IRoverManager, IRoverLocator {
	
	public Rover(Point position, String name) {
		super(position, name);
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 */
	private Point destination;
	/**
	 * 
	 */
	private Mission mission;
	/**
	 * 
	 */
	private boolean paused;
	/**
	 * 
	 */
	private boolean sleeping;
	/**
	 * 
	 */
	private IStrategy strategy;
	/**
	 * 
	 */
	private IAccessManager accessManager;
	/**
	 * 
	 */
	private AbstractArea[] listAreas;

	/**
	 * 
	 * @param position 
	 * @param name 
	 * @param accessManager 
	 * @param listAreas 
	 */
	public Rover(Point position, String name, IAccessManager accessManager, IVisitableArea[] listAreas) {
		super(position, name);
		paused = false;
		sleeping = true;
		this.accessManager = accessManager;
		this.listAreas = (AbstractArea[]) listAreas;
		this.strategy = new Strategy1(); //By default
		
	}

	/**
	 * 
	 * @return 
	 */
	public Point getDestination() {
		return destination;
	}

	/**
	 * 
	 * @return 
	 */
	public Mission getMission() {
		return mission;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isPaused() {
		return paused;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isSleeping() {
		return sleeping;
	}

	/**
	 * 
	 * @return 
	 */
	public IStrategy getStrategy() {
		return strategy;
	}

	/**
	 * 
	 * @return 
	 */
	public IAccessManager getAccessManager() {
		return accessManager;
	}

	/**
	 * 
	 * @param destination 
	 * @return 
	 */
	public void setDestination(Point destination) {
	}

	/**
	 * 
	 * @return 
	 */
	public void goToNextPoint() {
	}

	/**
	 * 
	 * @param roverName 
	 * @return 
	 */
	public Point getLocation(String roverName) {
		return null;
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 * @param strategy 
	 */
	public boolean provideMission(Mission mission, IStrategy strategy) {
		return true;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean pauseRover() {
		return true;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean continueRover() {
		return true;
	}

	/**
	 * 
	 * @param strategy 
	 * @return 
	 */
	public boolean changeStrategy(IStrategy strategy) {
		return true;
	}

	/**
	 * 
	 * @param roverName 
	 * @return 
	 */

	/**
	 * 
	 * @return 
	 */
	public IVisitableArea[] isInArea() {
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public void routine() {
	}

	/**
	 * 
	 * @return 
	 */

	/**
	 * 
	 * @return 
	 */
	public boolean removeMission() {
		mission = null;
		return true;
	}

	@Override
	public IVisitableArea[] getAreas() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return null;
	}
};
