// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.IVisitableArea;

/************************************************************/
/**
 * 
 */
public abstract class AbstractArea {
};
