// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.AccessController;
import rover.IAccessManager;
import rover.Rover;

/************************************************************/
/**
 * 
 */
public class AccessManager implements IAccessManager {
	/**
	 * 
	 */
	public AccessController[] listAreaController;

	/**
	 * 
	 * @param listAreaController 
	 */
	public void AccessManager(AccessController[] listAreaController) {
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public AccessController isInAreaController(Rover rover) {
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public void releaseArea(Rover rover) {
	}

	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public void acquireAccess(Rover rover) {
	}
};
