// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.Rover;

/************************************************************/
/**
 * 
 */
public interface IAccessManager {
	/**
	 * 
	 * @param rover 
	 * @return 
	 */
	public void manageAccess(Rover rover);
};
