// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

/************************************************************/
/**
 * 
 */
public interface IOperatorRewardPointsView {
	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void notifyRewardPoints(int rewardPoints);

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoints();

	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void resetRewardPoints(int rewardPoints);
};
