// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import project.Point;

/************************************************************/
/**
 * 
 */
public interface IPointAchieved {
	/**
	 * 
	 * @param savePoint 
	 * @return 
	 * @param roverName 
	 */
	public void achievedPoint(Point savePoint, RobotAvatar rover);
};
