// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import project.Point;
import rover.Rover;

/************************************************************/
/**
 * 
 */
public interface IRewardPoints {
	/**
	 * 
	 * @param rover 
	 * @param point 
	 * @return 
	 */
	public void calculateRewardPoints(Rover rover, Point point);

	/**
	 * 
	 * @param points 
	 * @return 
	 */
	public void updateRewardPoints(int[] points);
};
