// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.IStrategy;
import rover.Mission;

/************************************************************/
/**
 * 
 */
public interface IRoverManager {
	/**
	 * 
	 * @param mission 
	 * @return 
	 * @param strategy 
	 */
	public boolean provideMission(Mission mission, IStrategy strategy);

	/**
	 * 
	 * @return 
	 */
	public boolean pauseRover();

	/**
	 * 
	 * @return 
	 */
	public boolean continueRover();

	/**
	 * 
	 * @param strategy 
	 * @return 
	 */
	public boolean changeStrategy(IStrategy strategy);
};
