// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.Rover;

/************************************************************/
/**
 * 
 */
public interface IStrategy {
	/**
	 * 
	 * @param rover 
	 */
	public void applyBehaviour(Rover rover);
};
