// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.Mission;
import rover.Strategy;

/************************************************************/
/**
 * 
 */
public interface IStrategyManager {
	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean provideMission(Mission mission);

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean pauseStrategy(Mission mission);

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean continueStrategy(Mission mission);

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean changeMission(Mission mission);

	/**
	 * 
	 * @return 
	 */
	public Strategy getStrategyPaused();
};
