// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.IVisitorProcedure;

/************************************************************/
/**
 * 
 */
public interface IVisitableRover {
	/**
	 * 
	 * @param visitor 
	 */
	public void accept(IVisitorProcedure visitor);
};
