// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.LogicalArea;
import rover.PhysicalArea;
import rover.Rover;

/************************************************************/
/**
 * 
 */
public interface IVisitorProcedure {
	/**
	 * 
	 * @param logicalArea 
	 * @param rover 
	 * @return 
	 */
	public void visit(LogicalArea logicalArea, Rover rover);

	/**
	 * 
	 * @param physicalArea 
	 * @return 
	 * @param rover 
	 */
	public void visit(PhysicalArea physicalArea, Rover rover);
};
