// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.IVisitableRover;
import rover.IVisitorProcedure;

/************************************************************/
/**
 * 
 */
public interface IVisitableArea {
	/**
	 * 
	 * @param procedure 
	 * @param rover 
	 * @return 
	 */
	public void accept(IVisitorProcedure procedure, IVisitableRover rover);
};
