// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import java.util.LinkedList;
import project.Point;

/************************************************************/
/**
 * 
 */
public class Mission {
	private LinkedList<Point> pointsToReach;
	private LinkedList<Point> pointsReached;

	
	public Mission(LinkedList<Point> pointsToReach){
		this.pointsToReach = pointsToReach;
		this.pointsReached = new LinkedList<Point>();
	}
	
	public LinkedList<Point> getPointsToReach(){
		return this.pointsToReach;
	}
	
	public LinkedList<Point> getPointsReached(){
		return this.pointsReached;
	}
	
	public void pointReached(){
		if(!pointsToReach.isEmpty()) {
			pointsReached.add(pointsToReach.removeFirst());
		}
	}
	
	public Point getNextPoint() {
		if(!pointsToReach.isEmpty()) {
			return pointsToReach.getFirst();
		}
		else {
			return null;
		}
	}
};