// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import java.util.List;
import project.Point;
import rover.IMissionManager;
import rover.Mission;
import rover.Rover;

/************************************************************/
/**
 * 
 */
public class MissionManager implements IMissionManager {
	/**
				 * 
				 */
				public List<Mission> list<mission>;
	/**
				 * 
				 */
				public List<Rover> list<rover>;

	/**
	 * 
	 * @param rovers 
	 */
	public void MissionManager(Rover rovers) {
	}

	/**
	 * 
	 * @return 
	 */
	public Mission getMissions() {
	}

	/**
	 * 
	 * @return 
	 */
	public Rover getRovers() {
	}

	/**
	 * 
	 * @param roverName 
	 * @return 
	 */
	public boolean checkRoverAvailability(String roverName) {
	}

	/**
	 * 
	 * @return 
	 */
	public void achievedMission() {
	}

	/**
	 * 
	 * @return 
	 */
	public void achievedPoint() {
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean createMission(undefined mission) {
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean removeMission(undefined mission) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean removeAllMissions() {
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean pauseMission(undefined mission) {
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean continueMission(undefined mission) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean pauseAllMissions() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean continueAllMissions() {
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean removeMission(undefined mission) {
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean pauseMission(undefined mission) {
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public boolean continueMission(undefined mission) {
	}

	/**
	 * 
	 * @param points 
	 * @return 
	 */
	public boolean createMission(undefined points) {
	}

	/**
	 * 
	 * @param points 
	 * @return 
	 */
	public boolean createMission(Point points) {
	}

	/**
	 * 
	 * @param points 
	 * @return 
	 */
	public boolean createMission(Point points) {
	}

	/**
	 * 
	 * @param points 
	 * @return 
	 */
	public boolean createMission(Point points) {
	}

	/**
	 * 
	 * @return 
	 */
	public void achievedMission() {
	}

	/**
	 * 
	 * @param points 
	 * @return 
	 * @param rover 
	 */
	public boolean createMission(Point[] points, Rover rover) {
	}

	/**
	 * 
	 * @return 
	 */
	public void achievedPoint() {
	}
};
