// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import java.util.List;

import project.Point;

/************************************************************/
/**
 * 
 */
public class Mission {
	/**
	 * 
	 */
	private List<Point> points;
	/**
	 * 
	 */
	private RobotAvatar rover;
	
	public Mission(List<Point> points, RobotAvatar rover){
		this.points = points;
		this.rover = rover;
	}
	
	public List<Point> getPoints(){
		return this.points;
	}
	
	public RobotAvatar getRover(){
		return this.rover;
	}
};