// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import project.Point;

/************************************************************/
/**
 * 
 */
public class Mission {
	/**
	 * 
	 */
	public Point[] points;
	/**
	 * 
	 */
	public String roverName;
	
	public Mission(Point[] points, String roverName) {
		this.points = points;
		this.roverName = roverName;
	}
};
