// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.IOperatorEnvironmentView;

/************************************************************/
/**
 * 
 */
public class NTOperatorEnvironmentView implements IOperatorEnvironmentView {

	public void updateLocation() {
		// TODO Auto-generated method stub
		
	}

	public void updateEnvironmentStatus() {
		// TODO Auto-generated method stub
		
	}

	public void updateMissionProgress() {
		// TODO Auto-generated method stub
		
	}
};
