// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.IOperatorRewardPointsView;

/************************************************************/
/**
 * 
 */
public class NTOperatorRewardPointsView implements IOperatorRewardPointsView {
	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void notifyRewardPoints(int rewardPoints) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoints() {
		return 0;
	}

	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void resetRewardPoints(int rewardPoints) {
	}
};
