// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import project.Point;
import rover.IOperatorCreateMissionView;
import rover.IOperatorEnvironmentView;
import rover.IOperatorFaultView;
import rover.IOperatorRewardPointsView;

/************************************************************/
/**
 * 
 */
public class Operator implements IOperatorFaultView {
	/**
	 * 
	 */
	public IOperatorCreateMissionView ioperatorrewardpointsview;
	/**
	 * 
	 */
	public IOperatorEnvironmentView ioperatorenvironmentview;
	/**
	 * 
	 */
	public IOperatorFaultView ioperatorfaultview;

	/**
	 * 
	 * @return 
	 */
	public void updateLocation() {
	}

	/**
	 * 
	 * @return 
	 */
	public void updateEnvironmentStatus() {
	}

	/**
	 * 
	 * @return 
	 */
	public void updateMissionProgress() {
	}

	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void notifyRewardPoints(int[] rewardPoints) {
	}

	/**
	 * 
	 * @param points 
	 * @param roverName 
	 */
	public void createMission(Point points, String roverName) {
	}

	public void notifyFault() {
		// TODO Auto-generated method stub
		
	}
};
