// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import project.Point;
import rover.IMissionManager;
import rover.IOperatorCreateMissionView;
import rover.IOperatorEnvironmentView;
import rover.IOperatorFaultView;
import rover.IOperatorRewardPointsView;
import rover.StrategyFactory;

/************************************************************/
/**
 * 
 */
public class Operator implements IOperatorFaultView {
	/**
	 * 
	 */
	public IOperatorCreateMissionView ioperatorrewardpointsview;
	/**
	 * 
	 */
	public IOperatorRewardPointsView ioperatorrewardpointsview;
	/**
	 * 
	 */
	public IOperatorEnvironmentView ioperatorenvironmentview;
	/**
	 * 
	 */
	public IOperatorFaultView ioperatorfaultview;
	/**
	 * 
	 */
	public StrategyFactory strategyfactory;

	/**
	 * 
	 * @return 
	 */
	public void updateLocation() {
	}

	/**
	 * 
	 * @return 
	 */
	public void updateMissionProgress() {
	}

	/**
	 * 
	 * @param rewardPoints 
	 * @return 
	 */
	public void notifyRewardPoints(int[] rewardPoints) {
	}

	/**
	 * 
	 * @param points 
	 * @param roverName 
	 */
	public void createMission(Point points, String roverName) {
	}
};
