// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import java.util.Map;
import project.Point;
import rover.IVisitorProcedure;
import rover.LogicalArea;
import rover.Rover;

/************************************************************/
/**
 * 
 */
public class ProcedureB implements IVisitorProcedure {
	/**
	 * 
	 */
	public map<Rover, int> map<rover, int>;
	/**
	 * 
	 * @param logicalArea 
	 * @param rover 
	 * @return 
	 */
	public void visit(Point logicalArea, Rover rover) {
	}

	/**
	 * 
	 * @param logicalArea 
	 * @param rover 
	 * @return 
	 */
	public void visit(LogicalArea logicalArea, Rover rover) {
	}
};
