// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import project.Point;
import rover.IRewardPoints;

/************************************************************/
/**
 * 
 */
public class ProcedureA implements IRewardPoints
 {
				/**
				 * 
				 */
				public int rewardPoint;

				public void calculateRewardPoints(String name, Point point) {
					// TODO Auto-generated method stub
					
				}

				public void updateRewardPoints(int[] points) {
					// TODO Auto-generated method stub
					
				}
};
