// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import project.Point;
import rover.IRewardPoints;
import rover.Rover;

/************************************************************/
/**
 * 
 */
public class ProcedureB implements IRewardPoints {
	/**
	 * 
	 */
	public int rewardPoint;

	/**
	 * 
	 * @param points 
	 * @return 
	 */
	public void updateRewardPoints(int[] points) {
	}

	/**
	 * 
	 * @param rover 
	 * @param point 
	 * @return 
	 */
	public void calculateRewardPoints(Rover rover, Point point) {
	}
};
