// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import java.util.Map;
import rover.IRewardPoints;
import rover.IRewardPointsManagar;
import rover.IRoverLocation;
import rover.ProcedureA;
import rover.ProcedureB;

/************************************************************/
/**
 * 
 */
public class RewardPointsManager implements IRewardPointsManagar {
	/**
				 * 
				 */
				private ProcedureA procedureA;
	/**
				 * 
				 */
				private ProcedureB procedureB;
	/**
	 * 
	 */
	private IRewardPoints currentProcedure;

	/**
	 * 
	 */
	public map<String, int> map<string, int>;
	/**
	 * 
	 * @return 
	 */
	private void updateProcedure() {
	}

	/**
	 * 
	 * @param additionalPoint 
	 * @param nameRover 
	 * @return 
	 */
	public void setRewardPoints(int additionalPoint, String nameRover) {
	}

	public void updateRewardPoints() {
		// TODO Auto-generated method stub
		
	}
};
