// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import java.util.Map;
import rover.IOperatorRewardPointsView;
import rover.IRewardPointsManagar;
import rover.IVisitableRover;
import rover.IVisitorProcedure;
import rover.runnable;

/************************************************************/
/**
 * 
 */
public class RewardPointsManager implements IRewardPointsManagar, runnable
 {
				/**
				 * 
				 */
				private IVisitorProcedure[] procedureList;
				/**
				 * 
				 */
				private map<Rover, int> map<Rover, int>;
};
