// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import java.util.List;
import java.util.ArrayList;

import project.Point;

/************************************************************/
/**
 * 
 */
public class Strategy {
	/**
	 * 
	 */
	private Mission mission;
	/**
	 * 
	 */
	private List<Point> pointHistory;

	public Strategy(Mission mission){
		this.mission = mission;
		this.pointHistory = new ArrayList<Point>();
	}
	
	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public void setMission(Mission mission){
		this.mission = mission;
	}
	
	public Mission getMission(){
		return this.mission;
	}

	/**
	 * 
	 * @param point 
	 * @return 
	 */
	public void addPointHistory(Point point){
		this.pointHistory.add(point); 
	}

	/**
	 * 
	 * @return 
	 */
	public Point getLastPoint() {
		return this.pointHistory.get(this.pointHistory.size() - 1);
	}
	
	public List<Point> getAllPoints() {
		return this.pointHistory;
	}
};
