// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import java.util.HashSet;
import java.util.Set;

import project.Point;
import rover.IMissionAchieved;
import rover.IPointAchieved;
import rover.IStrategyManager;
import rover.Mission;
import rover.Strategy;

/************************************************************/
/**
 * 
 */
public class StrategyManager implements IPointAchieved, IStrategyManager {
	
	boolean roverBusy = false;
	RoverList roverList = new RoverList();
	Set<Rover> rovers = roverList.getRovers();
	/**
	 * 
	 */
	public Strategy[] strategy;

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	private void initialiseStrategy(Mission mission) {
	}

	/**
	 * 
	 * @param roverName 
	 * @return 
	 */
	private boolean checkRoverAvailability(String roverName) {
		return false;
	}

	/**
	 * 
	 * @param roverName 
	 * @return 
	 */
	private Point defineNextPoint(String roverName) {
		return null;
	}

	/**
	 * 
	 * @param point 
	 * @param roverName 
	 * @return 
	 */
	private void providePointToRover(Point point, String roverName) {
	      /*
		for (Rover rover : rovers) {
	          if (rover.equals(roverName)) 
	            rover.goTo(point);
	            }
	            */
	}

	/**
	 * 
	 * @return 
	 */
	private void mainProcedure() {
		
	}

	public boolean provideMission(Mission mission) {
		/*
		for (int i = 0; i < mission.points.length; i++) {
			while (roverBusy) {
				
			}
				providePointToRover(mission.points[i], "Rover 1");
				roverBusy = true;
			} 
			*/
		return true;
	}

	public boolean pauseStrategy(Mission mission) {
		// TODO Auto-generated method stub
		return false;
	}

	public boolean continueStrategy(Mission mission) {
		// TODO Auto-generated method stub
		return false;
	}

	public boolean changeMission(Mission mission) {
		// TODO Auto-generated method stub
		return false;
	}

	public Strategy getStrategyPaused() {
		// TODO Auto-generated method stub
		return null;
	}

	public void achievedPoint(Point savePoint, String roverName) {
		roverBusy = false;
		
	}
};
