// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.IStrategy;
import rover.Rover;

/************************************************************/
/**
 * 
 */
public class Strategy1 implements IStrategy {
	/**
	 * 
	 * @param rover 
	 */
	public void computeStrategy(undefined rover) {
	}

	/**
	 * 
	 * @param rover 
	 */
	public void computeStrategy(Rover rover) {
	}

	/**
	 * 
	 * @param rover 
	 */
	public void applyBehaviour(Rover rover) {
	}
};
