// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import project.Point;
import rover.IMissionAchieved;
import rover.IPointAchieved;
import rover.IStrategyManager;
import rover.Mission;
import rover.Strategy;

/************************************************************/
/**
 * 
 */
public class StrategyManager implements IPointAchieved, IStrategyManager {
	/**
	 * 
	 */
	public Strategy[] strategy;

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	private void initialiseStrategy(Mission mission) {
	}

	/**
	 * 
	 * @param roverName 
	 * @return 
	 */
	private boolean checkRoverAvailability(String roverName) {
		return false;
	}

	/**
	 * 
	 * @param roverName 
	 * @return 
	 */
	private Point defineNextPoint(String roverName) {
		return null;
	}

	/**
	 * 
	 * @param point 
	 * @param roverName 
	 * @return 
	 */
	private void providePointToRover(Point point, String roverName) {
	}

	/**
	 * 
	 * @return 
	 */
	private void mainProcedure() {
	}

	public boolean provideMission(Mission mission) {
		// TODO Auto-generated method stub
		return false;
	}

	public boolean pauseStrategy(Mission mission) {
		// TODO Auto-generated method stub
		return false;
	}

	public boolean continueStrategy(Mission mission) {
		// TODO Auto-generated method stub
		return false;
	}

	public boolean changeMission(Mission mission) {
		// TODO Auto-generated method stub
		return false;
	}

	public Strategy getStrategyPaused() {
		// TODO Auto-generated method stub
		return null;
	}

	public void achievedPoint(Point savePoint, String roverName) {
		// TODO Auto-generated method stub
		
	}
};
