// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.Area;
import rover.IStrategy;

/************************************************************/
/**
 * 
 */
public class Strategy2 implements IStrategy {
	/**
	 * 
	 */
	public Area currentArea;
};
