// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import project.Point;
import rover.Mission;

/************************************************************/
/**
 * 
 */
public class Strategy {
	/**
	 * 
	 */
	private Mission mission;
	/**
	 * 
	 */
	private Point pointHistory;

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public void setMission(Mission mission) {
	}

	/**
	 * 
	 * @param point 
	 * @return 
	 */
	public void addPointHistory(Point point) {
	}

	/**
	 * 
	 * @return 
	 */
	public Point getLastPoint() {
		return null;
	}
};
