// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.IOperatorCreateMissionView;

/************************************************************/
/**
 * 
 */
public class TOperatorCreateMissionView implements IOperatorCreateMissionView {
};
