// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rover;

import rover.IOperatorCreateMissionView;

/************************************************************/
/**
 * 
 */
public class TOperatorCreateMissionView implements IOperatorCreateMissionView {

	public void createMission(int points, String roverName) {
		// TODO Auto-generated method stub
		
	}
};
